import Footer from "@/components/ui/Footer";
import Head from "next/head";

export default function Terms() {
  return (
    <>
      {/* SEO Meta Tags */}
      <Head>
        <title>Terms and Conditions | CloudPractitioner</title>
        <meta
          name="description"
          content="Read the terms and conditions for using the CloudPractitioner platform to prepare for the AWS Cloud Practitioner certification."
        />
        <meta name="robots" content="index, follow" />
        <meta
          name="keywords"
          content="Cloud Practitioner, AWS certification, terms of use, CloudPractitioner, exam platform"
        />
        <meta name="author" content="CloudPractitioner" />
        <link rel="canonical" href="https://www.cloudpractitioner.io/terms" />
      </Head>

      <div className="relative isolate overflow-hidden bg-white px-6 py-12 lg:px-8">
        <div className="mx-auto max-w-3xl text-gray-900">
          <h1 className="text-3xl font-bold mb-6">
            Terms and Conditions – CloudPractitioner
          </h1>
          <p className="mb-4">Last updated: June 15, 2025</p>

          <h2 className="text-xl font-semibold mt-6 mb-2">
            1. Service Description
          </h2>
          <p className="mb-4">
            CloudPractitioner is an online platform that helps users prepare for
            the AWS Cloud Practitioner certification. The platform provides
            AI-generated practice exams, flashcards, explanations, and progress
            tracking for educational purposes.
          </p>

          <h2 className="text-xl font-semibold mt-6 mb-2">2. Usage Terms</h2>
          <p className="mb-4">
            - This service is intended for personal and educational use only.
            <br />
            - Redistribution, resale, or commercial use of the content generated
            by CloudPractitioner without written permission is strictly
            prohibited.
            <br />- You agree to provide accurate and truthful information when
            creating an account.
          </p>

          <h2 className="text-xl font-semibold mt-6 mb-2">3. Copyright</h2>
          <p className="mb-4">
            All materials generated by the platform, including source code,
            design, and features, are protected by copyright. CloudPractitioner
            retains all rights to its original content and intellectual
            property.
          </p>

          <h2 className="text-xl font-semibold mt-6 mb-2">
            4. Limitation of Liability
          </h2>
          <p className="mb-4">
            CloudPractitioner does not guarantee that the questions or content
            will match those found in the official AWS certification exams. It
            is your responsibility to verify and prepare accordingly.
          </p>

          <h2 className="text-xl font-semibold mt-6 mb-2">
            5. Payments & Subscriptions
          </h2>
          <p className="mb-4">
            Full access to platform features is provided through a one-time
            payment. Pricing details are available on the “Pricing” page. All
            transactions are securely processed via authorized payment
            providers.
          </p>

          <h2 className="text-xl font-semibold mt-6 mb-2">6. Privacy</h2>
          <p className="mb-4">
            Protecting your personal data is important to us. Please refer to
            our Privacy Policy to understand how we collect, store, and use your
            information.
          </p>

          <h2 className="text-xl font-semibold mt-6 mb-2">
            7. Changes to Terms
          </h2>
          <p className="mb-4">
            We reserve the right to update these terms at any time. Any changes
            will be published on this page. Continued use of the service
            constitutes your acceptance of the updated terms.
          </p>

          <h2 className="text-xl font-semibold mt-6 mb-2">8. Contact</h2>
          <p className="mb-4">
            If you have any questions or concerns regarding these Terms and
            Conditions, please contact us at:{" "}
            <strong>contact@cloud-practitioner.com</strong>
          </p>
        </div>
      </div>
    </>
  );
}
